Code review first project
lhscar56/ruby_first pull request #1
Opened 2019-10-08 19:56 UTC by lhscar56

2019-10-09 22:46 UTC, samgaco requested changes
Hi @JuanPabloGil and @lhscar56 :high_brightness: 

bubble_sort_by seems to not be working properly, please address it and submit back for another code review.

-----------------------

moving on :arrow_down: 
* **[For your next code review requests]**  Add a short summary of changes in Pull Request description

---------------------------

* ###### STATUS OF THE PROJECT: REQUESTED CHANGES :stop_sign:

2019-10-09 22:46 UTC, samgaco commented on bubble_sort_by.rb
> +    end
This end is closing the function, which seems to be a mistake.

2019-10-10 18:18 UTC, Oghenebrume50 requested changes
Hi, Team, everything works now, however stickler has not been added to this project yet, can we make that work, and fix every known error before requesting for a review. You can find stickler details on the [pathwright path](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/57421588/) for this project

Submit for review, when this is done :pray:

2019-10-11 18:54 UTC, BalintMendli requested changes
Hi @lhscar56 @JuanPabloGil ,

Great job on the project. 👏 

However, Stickler is still not working. Make sure get the filename `.stickler.yml` right.

Also
- authorize Stickler to have access to the repo [here](https://github.com/settings/installations),
- enable repo on https://stickler-ci.com/,

if you haven't done so already.

When it is working fix any lint errors the code may have.

**Please submit another review request when it's done.**

2019-10-12 10:28 UTC, bolah2009 approved these changes
Linter seems to be working fine now. 
It's a :+1: from me.

#### :heavy_check_mark: You can merge to master.

-----

# Let's make this Pull Request look more professional.
  - [NEXT PROJECT]: Use meaningful commits messages. [Learn more here](https://www.freecodecamp.org/news/level-you-up-to-awesome-commit-messages-a85558cb90e8/) and Check [this awesome article](https://chris.beams.io/posts/git-commit/)
  - [REQUIRED] Use meaningful names for  Pull Requests.
  - [REQUIRED] Add a short summary of changes in the Pull Request description.

# Rename PR
  ![rename PR](https://user-images.githubusercontent.com/36057474/63838245-ec569f80-c974-11e9-93a9-83a4db5c259f.gif)
-----
# Update PR description
  ![update-PR-description-html](https://user-images.githubusercontent.com/36057474/64305800-6e078800-cf88-11e9-82f0-04e13fd6cb8d.gif)

2019-10-14 15:07 UTC, merged